// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB72ptivDyOWr5hDV1z2WUElYlFh_UL2YI',
    appId: '1:615582581605:web:a324e2bfd1c1f38d96d78c',
    messagingSenderId: '615582581605',
    projectId: 'flutter-fb-1d2c7',
    authDomain: 'flutter-fb-1d2c7.firebaseapp.com',
    storageBucket: 'flutter-fb-1d2c7.appspot.com',
    measurementId: 'G-4G44X9FKW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAde_TD0ZkVkbSxDMIc9-K30-bPJJdOtjg',
    appId: '1:615582581605:android:c2c8cc1b1cf5e40296d78c',
    messagingSenderId: '615582581605',
    projectId: 'flutter-fb-1d2c7',
    storageBucket: 'flutter-fb-1d2c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbUqoSOYirTc-kXMkTHvnJb9KFIEAxsR0',
    appId: '1:615582581605:ios:6e60a6249cf2b4a996d78c',
    messagingSenderId: '615582581605',
    projectId: 'flutter-fb-1d2c7',
    storageBucket: 'flutter-fb-1d2c7.appspot.com',
    iosBundleId: 'com.example.appkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbUqoSOYirTc-kXMkTHvnJb9KFIEAxsR0',
    appId: '1:615582581605:ios:1721af97ebd0579496d78c',
    messagingSenderId: '615582581605',
    projectId: 'flutter-fb-1d2c7',
    storageBucket: 'flutter-fb-1d2c7.appspot.com',
    iosBundleId: 'com.example.appkFlutter.RunnerTests',
  );
}
